version: '2.2'
services: 
    mysql :
        image: mysql
        restart: always
        volumes: 
            - /Users/techmaster/Desktop/obo.sql:/docker-entrypoint-initdb.d/init.sql
        environment: 
            MYSQL_ROOT_PASSWORD : mysql 
            MYSQL_DATABASE : obo 
            MYSQL_USER : admin 
            MYSQL_PASSWORD : 123456
    
    web :
        image: project-maven:v1
        depends_on: 
            - mysql
        ports: 
            - "8005:8080"
        restart: always